Repository UENSA-Labs/social-media-app, pull requests merged in 2020-04, with the labels that each got.

#3 probando
  src/index.scss
Labels: ux/ui

#6 fix #5 arreglando margen
  src/index.scss
Labels: bug

#9 New Navbar
  docs/asset-manifest.json
  docs/iframe.html
  docs/index.html
  docs/main.03e85bc75dcc22eef9f4.bundle.js
  docs/main.03e85bc75dcc22eef9f4.bundle.js.map
  docs/main.11eebc5dc57c8d1cdf99.bundle.js
  docs/main.11eebc5dc57c8d1cdf99.bundle.js.map
  docs/main.61547d805fba39a88a94.bundle.js
  docs/main.da98d98d2287918f6f3a.bundle.js
  docs/precache-manifest.617aeb0bf51ad9135ab25b26b1c988ed.js
  docs/precache-manifest.8f660771fac5c7c509fe4dfe4ec6fff8.js
  docs/runtime~main.03e85bc75dcc22eef9f4.bundle.js.map
  docs/runtime~main.11eebc5dc57c8d1cdf99.bundle.js
  docs/runtime~main.11eebc5dc57c8d1cdf99.bundle.js.map
  docs/runtime~main.411d3c3c7829aaabb366.bundle.js
  docs/service-worker.js
  docs/vendors~main.03e85bc75dcc22eef9f4.bundle.js
  docs/vendors~main.03e85bc75dcc22eef9f4.bundle.js.map
  docs/vendors~main.10718844ab6687519ef8.bundle.js
  docs/vendors~main.11eebc5dc57c8d1cdf99.bundle.js
  docs/vendors~main.11eebc5dc57c8d1cdf99.bundle.js.LICENSE.txt
  docs/vendors~main.11eebc5dc57c8d1cdf99.bundle.js.map
  docs/vendors~main.d4a9aa08817b3ba785b0.bundle.js
  package-lock.json
  package.json
  src/components/index.stories.js
  yarn.lock
Labels: WIP / do not merge, enhancement, ux/ui

#11 Add theme Provider
  src/components/Header/index.jsx
  src/containers/Home/Home.jsx
  src/containers/Home/styles.module.scss
  src/context/README.md
  src/context/ThemeProvider.jsx
  src/index.jsx
Labels: enhancement, ux/ui

#13 Dan/add i18n
  package-lock.json
  package.json
  src/components/Header/index.jsx
  src/containers/App/index.jsx
  src/containers/Home/Home.jsx
  src/context/LocaleProvider.jsx
  src/i18n/locales/Portuguese.json
  src/i18n/locales/de.js
  src/i18n/locales/en.js
  src/i18n/locales/es.js
  src/i18n/locales/fr.js
  src/i18n/locales/pt.js
  src/i18n/locales/pt.json
  src/i18n/translation.js
  src/i18n/translations.js
  src/index.jsx
  src/types/router.js
Labels: enhancement
